# From https://devkitpro.org/wiki/Getting_Started/devkitARM
language: cpp
compiler: gcc

install:
  - pwd
  - my_github=${PWD##*/} 
  - echo $my_github
  - sudo ./build_libnds_64

script:
  - export DEVKITPRO=/opt/devkitpro
  - export DEVKITARM=$DEVKITPRO/devkitARM
  # Do not call qmake, this will not work
  - cd ~/build/carmenijsebaart/$my_github
  - ./build_music
  - make
  - if [[ -f NDSgame.nds ]]; then echo "YES :-)"; else echo "NO :-("; fi

